@startsalt SignedInFlatmate
{
    {Flattie.com}
    {<u>Your one-stop shop for flatmate management}
    {
        [<b>Home] | [<b>Shopping List] | [<b>Chore List] | [<b>Rent Calculator] | [<b>Join Flat / Flat Info] | [Tickets] | [<b>About] | [<b>Log Out]
    }
}
@endsalt