name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with tests and coverage
      run: |
        ./gradlew build
        ./gradlew jacocoTestReport
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: coverage-report
        path: |
          build/reports/jacoco/test/html/
          build/reports/jacoco/test/jacocoTestReport.xml
        if-no-files-found: warn  # Prevents failure if reports missing