name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Gradle Wrapper
      run: |
        if [ ! -f "./gradlew" ]; then
          echo "Missing gradlew file!"
          exit 1
        fi
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build with tests
      run: ./gradlew build
    
    - name: Generate coverage report
      run: ./gradlew jacocoTestReport
      
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/reports/jacoco/test/